trigger: none

pr:
  branches:
    include:
    - main

pool:
  name: NetCore-Public
  demands:
  - ImageOverride -equals windows.vs2026.amd64.open

stages:
- template: /eng/pipelines/dotnet-package-skills/stage.yml
