trigger: none

pr:
  branches:
    include:
    - main

pool:
  name: NetCore-Public
  demands:
  - ImageOverride -equals windows.vs2026.amd64.open

stages:
- template: dotnet-package-skills/stage.yml
  parameters:
    isOfficialBuild: false
    releaseBuild: false
